### ISSUE TITLE
建议把测试数据做图表比较一下，这样更加直观

### ISSUE THREAD

**Issue by kiwenlau** [soulteary/redirect-test#1]
很赞，最近刚好在想怎么做短链接服务

建议把测试数据做图表比较一下，这样比较起来更加直观。

**Comment by soulteary** [comment]
这个仓库的目的是为了让读者自行测试，所以去掉了许多没必要的东西，包括 README、协议、图表。

实际上，我在文章中有写出，在评估应用性能指标的时候，还需要关注系统指标，所以图表呈现也势必会显得非常混乱。

欢迎写一篇文章，作为类似内容的补充，:)
